version: '3'
services:

  #PHP Service
  php8-app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: app-voyagego #custom image
    container_name: php8-app
    restart: always
    environment:
      SERVICE_NAME: php8-service
      SERVICE_TAGS: dev
    volumes:
      - ./:/var/www/html
      - ./.docker/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - network-nginx
      - network-db-postgres

  #Nginx Service
  webserver-nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    container_name: webserver_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/app.conf:/etc/nginx/conf.d/app.conf:ro
    depends_on:
      - db-postgres
      - php8-app
    networks:
      - network-nginx

  #Postgres database service
  db-postgres:
    image: postgres:13
    container_name: postgress_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: yoyagego
      POSTGRES_USER: voyagegouser
      POSTGRES_PASSWORD: P@ss@pp
      SERVICE_TAGS: dev
      SERVICE_NAME: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - network-db-postgres

#Networks
networks:
  network-nginx:
  network-db-postgres:

#Volumes
volumes:
  db-data:
    driver: local
