version: '3.7'
services:

  #PHP Service
  php8-app:
    build:
      args:
        user: www-app
        uid: 1000
      context: .
      dockerfile: .docker/Dockerfile
    image: app-voyagego #custom image
    container_name: php8_app
    restart: always
    volumes:
      - ./:/var/www/
      - ./.docker/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./.docker/www.conf:/usr/local/etc/php/conf.d/www.conf
    networks:
      - network-nginx
      - network-db-postgres

  #Nginx Service
  webserver-nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    image: webserver-nginx
    container_name: webserver_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/
      - ./.docker/nginx/app.conf:/etc/nginx/conf.d/app.conf:ro
    depends_on:
      - db-postgres
      - php8-app
    networks:
      - network-nginx

  #Postgres database service
  db-postgres:
    image: postgres:13.2-alpine
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: voyagego
      POSTGRES_USER: voyagego_admin
      POSTGRES_PASSWORD: Passwd
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - network-db-postgres

#Networks
networks:
  network-nginx:
  network-db-postgres:

#Volumes
volumes:
  db-data:
    driver: local
